# Generated by Django 3.0.4 on 2020-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=50)),
                ('details_url', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField()),
                ('created_at', models.FloatField()),
            ],
        ),
    ]
