# Generated by Django 3.0.4 on 2020-03-29 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteVideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='avatar',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='details_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
