# Generated by Django 3.0.4 on 2020-03-29 05:07

from django.db import migrations, models
import favoriteVideo.models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteVideo', '0002_auto_20200329_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=favoriteVideo.models.next_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.URLField(default='https://https://static.hdslb.com/images/akari.jpg')),
                ('details_url', models.URLField(default='https://space.bilibili.com/43389575/')),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(default=favoriteVideo.models.next_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('thumb', models.URLField(default='https://i2.hdslb.com/bfs/archive/100ca0eb1a1f3978e6f4a0f0dce3b0133fbf2a88.png')),
                ('details_url', models.URLField(default='https://www.bilibili.com/video/BV16b411S7Pu')),
                ('is_favorite', models.BooleanField(default=False)),
                ('from_web', models.CharField(default='bilibili', max_length=20)),
                ('public_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='follow',
            name='avatar',
            field=models.URLField(default='https://https://static.hdslb.com/images/akari.jpg'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='details_url',
            field=models.URLField(default='https://space.bilibili.com/43389575/'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.CharField(default=favoriteVideo.models.next_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
